import React, { useEffect, useMemo, useState } from 'react';
import { subscribeToCollection, confirmAppointment, updateAppointmentStatus, updateTeleconsultationStatus, updateDiagnosticRequestStatus, updateReferralStatus, updateEmergencyCaseStatus } from './dataStore';
import { FACILITIES } from './facilityRegistry';

const statuses = ['NEW', 'ACKNOWLEDGED', 'DISPATCHED', 'RECEIVED', 'CLOSED'];
const card = { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 14, padding: 16, marginBottom: 12 };

export function PHCHospitalPortal({ userProfile, lang, onSwitchPortal }) {
  const [facilityId, setFacilityId] = useState(userProfile?.facilityId || 'bhimavaram-care-desk');
  const [data, setData] = useState({ appointments: [], teleconsultations: [], diagnostic_requests: [], referrals: [], emergency_cases: [], triage_records: [] });
  const [tab, setTab] = useState('Overview');
  const facility = FACILITIES.find((x) => x.id === facilityId) || FACILITIES[0];
  useEffect(() => {
    const names = Object.keys(data);
    const unsubs = names.map((name) => subscribeToCollection(name, (items) => setData((old) => ({ ...old, [name]: items }))));
    return () => unsubs.forEach((fn) => fn && fn());
  }, []);
  const inFacility = (item) => item.targetFacilityId === facilityId || item.facilityId === facilityId || item.facility === facility.name || item.referredTo === facility.name;
  const cases = useMemo(() => Object.fromEntries(Object.entries(data).map(([key, items]) => [key, items.filter(inFacility)])), [data, facilityId]);
  const emergencies = cases.emergency_cases.filter((x) => x.status !== 'CLOSED');
  const Row = ({ item, children, accent = '#0f6cbd' }) => <div style={{ ...card, borderLeft: `5px solid ${accent}` }}><strong>{item.patientName || 'Citizen'} </strong><span style={{ color: '#64748b' }}>• {item.status || 'REQUESTED'}</span><div style={{ fontSize: 13, marginTop: 6 }}>{item.reason || item.chiefComplaint || item.testType || item.appointmentType || item.mode || 'Care request'}{item.village ? ` • ${item.village}` : ''}</div><div style={{ fontSize: 12, color: '#64748b', marginTop: 4 }}>{item.appointmentDate || item.scheduledDate || item.createdAt}</div>{children}</div>;
  return <div className="page-content" style={{ maxWidth: 1040, margin: '16px auto', padding: 16 }}>
    <div style={{ ...card, background: '#083b66', color: 'white' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><h1 style={{ margin: 0, color: 'white', fontSize: 22 }}>PHC / Hospital Care Desk</h1><p style={{ margin: '5px 0 0', color: '#dbeafe' }}>Live clinical intake, referrals, diagnostics and teleconsult coordination</p></div><button className="btn-outline" onClick={onSwitchPortal}>All portals</button></div><label style={{ display: 'block', marginTop: 12, fontSize: 12 }}>Working facility <select value={facilityId} onChange={(e) => setFacilityId(e.target.value)} style={{ marginLeft: 8, padding: 7, borderRadius: 8 }}>{FACILITIES.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
    {emergencies.length > 0 && <div style={{ ...card, background: '#fff1f2', borderColor: '#f43f5e', color: '#9f1239' }}>🚨 <strong>108 care-desk alert: {emergencies.length} active emergency case{emergencies.length > 1 ? 's' : ''}</strong> — acknowledge and coordinate with the official emergency service.</div>}
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 14 }}>{['Overview','Emergencies','Appointments','Consultations','Diagnostics','Referrals'].map((x) => <button key={x} onClick={() => setTab(x)} className={tab === x ? 'btn-primary' : 'btn-outline'}>{x}</button>)}</div>
    {tab === 'Overview' && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))', gap: 12 }}>{[['Emergency alerts', emergencies.length, '#dc2626'],['Appointments', cases.appointments.length, '#0f6cbd'],['Consultations', cases.teleconsultations.length, '#7c3aed'],['Diagnostics', cases.diagnostic_requests.length, '#0d9488'],['Referrals', cases.referrals.length, '#d97706']].map(([label,value,color]) => <div key={label} style={{ ...card, margin: 0, borderTop: `4px solid ${color}` }}><div style={{ color: '#64748b', fontSize: 12 }}>{label}</div><strong style={{ fontSize: 30 }}>{value}</strong></div>)}</div>}
    {tab === 'Emergencies' && (cases.emergency_cases.length ? cases.emergency_cases.map((x) => <Row key={x.id} item={x} accent="#dc2626"><div style={{ marginTop: 10, display: 'flex', gap: 8, flexWrap: 'wrap' }}>{statuses.map((s) => <button key={s} className="btn-outline" disabled={x.status === s} onClick={() => updateEmergencyCaseStatus(x.id, s)}>{s}</button>)}<a className="btn-danger" href="tel:108">Call 108</a></div></Row>) : <p>No routed emergency cases.</p>)}
    {tab === 'Appointments' && (cases.appointments.length ? cases.appointments.map((x) => <Row key={x.id} item={x}><div style={{ marginTop: 10, display: 'flex', gap: 8 }}><button className="btn-primary" onClick={() => confirmAppointment(x.id)}>Confirm / token</button><button className="btn-outline" onClick={() => updateAppointmentStatus(x.id, 'COMPLETED')}>Complete</button></div></Row>) : <p>No appointment requests for this facility.</p>)}
    {tab === 'Consultations' && (cases.teleconsultations.length ? cases.teleconsultations.map((x) => <Row key={x.id} item={x} accent="#7c3aed"><div style={{ marginTop: 10, display: 'flex', gap: 8, flexWrap: 'wrap' }}>{x.meetingUrl && <a className="btn-primary" target="_blank" rel="noreferrer" href={x.meetingUrl}>Join video/audio room</a>}<button className="btn-outline" onClick={() => updateTeleconsultationStatus(x.id, 'READY')}>Mark ready</button><button className="btn-outline" onClick={() => updateTeleconsultationStatus(x.id, 'COMPLETED')}>Complete</button></div></Row>) : <p>No teleconsultation requests for this facility.</p>)}
    {tab === 'Diagnostics' && (cases.diagnostic_requests.length ? cases.diagnostic_requests.map((x) => <Row key={x.id} item={x} accent="#0d9488"><div style={{ marginTop: 10 }}><button className="btn-outline" onClick={() => updateDiagnosticRequestStatus(x.id, 'SAMPLE_COLLECTED')}>Sample collected</button> <button className="btn-outline" onClick={() => updateDiagnosticRequestStatus(x.id, 'RESULT_READY')}>Result ready</button></div></Row>) : <p>No diagnostic requests for this facility.</p>)}
    {tab === 'Referrals' && (cases.referrals.length ? cases.referrals.map((x) => <Row key={x.id} item={x} accent="#d97706"><div style={{ marginTop: 10 }}><button className="btn-outline" onClick={() => updateReferralStatus(x.id, 'ACCEPTED')}>Accept referral</button> <button className="btn-outline" onClick={() => updateReferralStatus(x.id, 'COMPLETED')}>Complete</button></div></Row>) : <p>No referrals for this facility.</p>)}
  </div>;
}
